#!/bin/bash

# detect interactive shell
case "$-" in
    *i*) INTERACTIVE=1 ;;
    *)   unset INTERACTIVE ;;
esac
 
# detect login shell
case "$0" in
    -*) LOGIN=1 ;;
    *)  unset LOGIN ;;
esac

# Basic variables
: ${HOME=~}
: ${LOGNAME=$(id -un)}
: ${UNAME=$(uname)}

# bring in system bashrc
test -r /etc/bashrc &&
      . /etc/bashrc

# fuck that you have new mail shit
unset MAILCHECK

# Aliases
alias ls='ls -G'
alias vi='vim'
alias duh='du -h -d=1'
alias fn='find . -name'
alias hi='history | tail -20'

# Ls colors & grepping
export LSCOLORS="exfxcxdxbxegedabagacad"
export CLICOLOR=true
export GREP_OPTIONS='--color=auto'

# Prompt
RED="\[\033[0;31m\]"
YELLOW="\[\033[0;33m\]"
GREY="\[\033[0;97m\]"
BLUE="\[\033[0;34m\]"
PS_CLEAR="\[\033[0m\]"
SCREEN_ESC="\[\033k\033\134\]"
WHITE="\[\033[0;37m\]"
GREEN="\[\033[0;32m\]"

# First the rules for users
if [ "$LOGNAME" = "root" ]; then
    COLOR1="${RED}"
    P="#"
else 
    COLOR1="${WHITE}"
    P="$"
fi
  
# Now color based on host
if which "hostname" > /dev/null && hostname | grep -iq 'Franz'; then
	HNAME="franz"
    COLOR2="${GREEN}"
elif which "hostname" > /dev/null && hostname | grep -iq 'archie'; then
	HNAME="archie"
    COLOR2="${BLUE}"
elif which "hostname" > /dev/null && hostname | grep -iq 'Alu'; then
	HNAME="alu"
	COLOR2="${GREEN}"
fi

prompt_color() {
    PS1="${GREY}[${COLOR1}\u${GREY}@${COLOR2}${HNAME}${GREY}:${COLOR1}\W${GREY}]${COLOR2}$P${PS_CLEAR} "
    PS2="\[[33;1m\]continue \[[0m[1m\]> "
}

prompt_sbox() {
    PS1="${GREY}[${COLOR1}sbox${GREY}-${YELLOW}`/scratchbox/tools/bin/sb-conf current`${GREY}:${COLOR1}\W${GREY}]${COLOR2}$P${PS_CLEAR} "
    PS2="\[[33;1m\]continue \[[0m[1m\]> "
}

# MOTD

test -n "$INTERACTIVE" -a -n "$LOGIN" && {
    uname -npsr
}

if [ "$_SBOX_SHELL_PID" != "" ]; then
    prompt_sbox
else
    prompt_color
fi

# push SSH public key to another box
push_ssh_cert() {
    local _host
    test -f ~/.ssh/id_dsa.pub
    for _host in "$@";
    do
        echo $_host
        ssh $_host 'cat >> ~/.ssh/authorized_keys' < ~/.ssh/id_dsa.pub
    done
}

export GIT_EDITOR=nano
export EDITOR=nano
export SVN_EDITOR=nano
